[package]
name = "Walrus"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2024.beta"
published-at = "0xe98079b13784b6156c7e45f19a011c489d29cee30489c4986758b230408bd6f3"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.48.0" }
WAL = { local = "../wal" }

[addresses]
walrus = "0xe98079b13784b6156c7e45f19a011c489d29cee30489c4986758b230408bd6f3"
