/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BugBountiesIndexImport } from './routes/bug-bounties/index'
import { Route as BugBountiesNewImport } from './routes/bug-bounties/new'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BugBountiesIndexRoute = BugBountiesIndexImport.update({
  id: '/bug-bounties/',
  path: '/bug-bounties/',
  getParentRoute: () => rootRoute,
} as any)

const BugBountiesNewRoute = BugBountiesNewImport.update({
  id: '/bug-bounties/new',
  path: '/bug-bounties/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bug-bounties/new': {
      id: '/bug-bounties/new'
      path: '/bug-bounties/new'
      fullPath: '/bug-bounties/new'
      preLoaderRoute: typeof BugBountiesNewImport
      parentRoute: typeof rootRoute
    }
    '/bug-bounties/': {
      id: '/bug-bounties/'
      path: '/bug-bounties'
      fullPath: '/bug-bounties'
      preLoaderRoute: typeof BugBountiesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bug-bounties/new': typeof BugBountiesNewRoute
  '/bug-bounties': typeof BugBountiesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bug-bounties/new': typeof BugBountiesNewRoute
  '/bug-bounties': typeof BugBountiesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bug-bounties/new': typeof BugBountiesNewRoute
  '/bug-bounties/': typeof BugBountiesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bug-bounties/new' | '/bug-bounties'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bug-bounties/new' | '/bug-bounties'
  id: '__root__' | '/' | '/bug-bounties/new' | '/bug-bounties/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugBountiesNewRoute: typeof BugBountiesNewRoute
  BugBountiesIndexRoute: typeof BugBountiesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugBountiesNewRoute: BugBountiesNewRoute,
  BugBountiesIndexRoute: BugBountiesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bug-bounties/new",
        "/bug-bounties/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bug-bounties/new": {
      "filePath": "bug-bounties/new.tsx"
    },
    "/bug-bounties/": {
      "filePath": "bug-bounties/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
