/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoadmapImport } from './routes/roadmap'
import { Route as DocsImport } from './routes/docs'
import { Route as ContactsImport } from './routes/contacts'
import { Route as IndexImport } from './routes/index'
import { Route as FindingIndexImport } from './routes/finding/index'
import { Route as BugBountyIndexImport } from './routes/bug-bounty/index'
import { Route as FindingNewImport } from './routes/finding/new'
import { Route as FindingFindingIdImport } from './routes/finding/$findingId'
import { Route as BugBountyNewImport } from './routes/bug-bounty/new'
import { Route as BugBountyBugBountyIdImport } from './routes/bug-bounty/$bugBountyId'

// Create/Update Routes

const RoadmapRoute = RoadmapImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRoute,
} as any)

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const ContactsRoute = ContactsImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FindingIndexRoute = FindingIndexImport.update({
  id: '/finding/',
  path: '/finding/',
  getParentRoute: () => rootRoute,
} as any)

const BugBountyIndexRoute = BugBountyIndexImport.update({
  id: '/bug-bounty/',
  path: '/bug-bounty/',
  getParentRoute: () => rootRoute,
} as any)

const FindingNewRoute = FindingNewImport.update({
  id: '/finding/new',
  path: '/finding/new',
  getParentRoute: () => rootRoute,
} as any)

const FindingFindingIdRoute = FindingFindingIdImport.update({
  id: '/finding/$findingId',
  path: '/finding/$findingId',
  getParentRoute: () => rootRoute,
} as any)

const BugBountyNewRoute = BugBountyNewImport.update({
  id: '/bug-bounty/new',
  path: '/bug-bounty/new',
  getParentRoute: () => rootRoute,
} as any)

const BugBountyBugBountyIdRoute = BugBountyBugBountyIdImport.update({
  id: '/bug-bounty/$bugBountyId',
  path: '/bug-bounty/$bugBountyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapImport
      parentRoute: typeof rootRoute
    }
    '/bug-bounty/$bugBountyId': {
      id: '/bug-bounty/$bugBountyId'
      path: '/bug-bounty/$bugBountyId'
      fullPath: '/bug-bounty/$bugBountyId'
      preLoaderRoute: typeof BugBountyBugBountyIdImport
      parentRoute: typeof rootRoute
    }
    '/bug-bounty/new': {
      id: '/bug-bounty/new'
      path: '/bug-bounty/new'
      fullPath: '/bug-bounty/new'
      preLoaderRoute: typeof BugBountyNewImport
      parentRoute: typeof rootRoute
    }
    '/finding/$findingId': {
      id: '/finding/$findingId'
      path: '/finding/$findingId'
      fullPath: '/finding/$findingId'
      preLoaderRoute: typeof FindingFindingIdImport
      parentRoute: typeof rootRoute
    }
    '/finding/new': {
      id: '/finding/new'
      path: '/finding/new'
      fullPath: '/finding/new'
      preLoaderRoute: typeof FindingNewImport
      parentRoute: typeof rootRoute
    }
    '/bug-bounty/': {
      id: '/bug-bounty/'
      path: '/bug-bounty'
      fullPath: '/bug-bounty'
      preLoaderRoute: typeof BugBountyIndexImport
      parentRoute: typeof rootRoute
    }
    '/finding/': {
      id: '/finding/'
      path: '/finding'
      fullPath: '/finding'
      preLoaderRoute: typeof FindingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/bug-bounty/$bugBountyId': typeof BugBountyBugBountyIdRoute
  '/bug-bounty/new': typeof BugBountyNewRoute
  '/finding/$findingId': typeof FindingFindingIdRoute
  '/finding/new': typeof FindingNewRoute
  '/bug-bounty': typeof BugBountyIndexRoute
  '/finding': typeof FindingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/bug-bounty/$bugBountyId': typeof BugBountyBugBountyIdRoute
  '/bug-bounty/new': typeof BugBountyNewRoute
  '/finding/$findingId': typeof FindingFindingIdRoute
  '/finding/new': typeof FindingNewRoute
  '/bug-bounty': typeof BugBountyIndexRoute
  '/finding': typeof FindingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/bug-bounty/$bugBountyId': typeof BugBountyBugBountyIdRoute
  '/bug-bounty/new': typeof BugBountyNewRoute
  '/finding/$findingId': typeof FindingFindingIdRoute
  '/finding/new': typeof FindingNewRoute
  '/bug-bounty/': typeof BugBountyIndexRoute
  '/finding/': typeof FindingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/docs'
    | '/roadmap'
    | '/bug-bounty/$bugBountyId'
    | '/bug-bounty/new'
    | '/finding/$findingId'
    | '/finding/new'
    | '/bug-bounty'
    | '/finding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/docs'
    | '/roadmap'
    | '/bug-bounty/$bugBountyId'
    | '/bug-bounty/new'
    | '/finding/$findingId'
    | '/finding/new'
    | '/bug-bounty'
    | '/finding'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/docs'
    | '/roadmap'
    | '/bug-bounty/$bugBountyId'
    | '/bug-bounty/new'
    | '/finding/$findingId'
    | '/finding/new'
    | '/bug-bounty/'
    | '/finding/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DocsRoute: typeof DocsRoute
  RoadmapRoute: typeof RoadmapRoute
  BugBountyBugBountyIdRoute: typeof BugBountyBugBountyIdRoute
  BugBountyNewRoute: typeof BugBountyNewRoute
  FindingFindingIdRoute: typeof FindingFindingIdRoute
  FindingNewRoute: typeof FindingNewRoute
  BugBountyIndexRoute: typeof BugBountyIndexRoute
  FindingIndexRoute: typeof FindingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DocsRoute: DocsRoute,
  RoadmapRoute: RoadmapRoute,
  BugBountyBugBountyIdRoute: BugBountyBugBountyIdRoute,
  BugBountyNewRoute: BugBountyNewRoute,
  FindingFindingIdRoute: FindingFindingIdRoute,
  FindingNewRoute: FindingNewRoute,
  BugBountyIndexRoute: BugBountyIndexRoute,
  FindingIndexRoute: FindingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts",
        "/docs",
        "/roadmap",
        "/bug-bounty/$bugBountyId",
        "/bug-bounty/new",
        "/finding/$findingId",
        "/finding/new",
        "/bug-bounty/",
        "/finding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contacts": {
      "filePath": "contacts.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx"
    },
    "/roadmap": {
      "filePath": "roadmap.tsx"
    },
    "/bug-bounty/$bugBountyId": {
      "filePath": "bug-bounty/$bugBountyId.tsx"
    },
    "/bug-bounty/new": {
      "filePath": "bug-bounty/new.tsx"
    },
    "/finding/$findingId": {
      "filePath": "finding/$findingId.tsx"
    },
    "/finding/new": {
      "filePath": "finding/new.tsx"
    },
    "/bug-bounty/": {
      "filePath": "bug-bounty/index.tsx"
    },
    "/finding/": {
      "filePath": "finding/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
