[package]
name = "lancer-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
sui-types = { workspace = true }
seal = { workspace = true }
walrus-core = { workspace = true }
