[package]
name = "lancer-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.48.0" }
seal = { workspace = true }
walrus-core = { workspace = true }
